services:
    liip.multiplex:
        class: Liip\MultiplexBundle\Controller\MultiplexController
        arguments:
            request: @request
            response: @response
            kernel: @kernel
            router: @router
        scope: prototype
